SELECT  HISTORY_ID,
        CAR_ID,
        DATE_FORMAT(START_DATE,"%Y%-%m-%d") as START_DATE, 
        DATE_FORMAT(END_DATE,"%Y-%m-%d") as END_DATE,
     if(DATEDIFF(END_DATE,START_DATE) >= 29, '장기 대여', '단기 대여') RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where DATE_FORMAT(START_DATE,"%Y-%m") LIKE '2022-09' 
ORDER BY 1 DESC;